Num_Caracs: ola_num_caracs_1.o Num_Caracs.o
	gcc $(CFLAGS) -o ola_num_caracs_1 ola_num_caracs_1.o Num_Caracs.o
ola_num_caracs_1.o: ola_num_caracs_1.c Num_Caracs.h
	gcc $(CFLAGS) -c ola_num_caracs_1.c
Num_Caracs.o: Num_Caracs.c Num_Caracs.h
	gcc $(CFLAGS) -c Num_Caracs.c
clean:
	rm -f *.o ola_num_caracs_1

